<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1-dev.13</Version>
    <VersionPrefix>0.1.13</VersionPrefix>
    <AssemblyVersion>0.1.13.0</AssemblyVersion>
    <FileVersion>0.1.13.0</FileVersion>
    <InformationalVersion>0.1-dev.13</InformationalVersion>
    <RootNamespace>CouchLink.SessionHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CouchLink.Host.Core\CouchLink.Host.Core.csproj" />
  </ItemGroup>
</Project>
